services:
  # AIO Search Tool - Streamlit Web Application
  - type: web
    name: aio-search-tool
    env: python
    runtime: python3.11
    buildCommand: |
      apt-get update
      apt-get install -y python3-dev libjpeg-dev zlib1g-dev
      python -m pip install --upgrade pip
      pip install --only-binary :all: numpy==1.24.3
      pip install --only-binary :all: pandas==2.1.4
      pip install --only-binary :all: pydantic==2.0.3
      pip install --only-binary :all: pillow==10.0.0
      pip install --only-binary :all: greenlet==2.0.2
      pip install --only-binary :all: -r requirements.txt
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.8"
      - key: PYTHONPATH
        value: "/app"
    startCommand: "streamlit run web_app.py --server.port $PORT --server.address 0.0.0.0 --server.headless true --browser.gatherUsageStats false"
    plan: free
    healthCheckPath: /_stcore/health
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: AIRTOP_API_KEY
        sync: false
      - key: STREAMLIT_SERVER_HEADLESS
        value: true
      - key: STREAMLIT_BROWSER_GATHER_USAGE_STATS
        value: false 