services:
  # AIO Search Tool - Streamlit Web Application
  - type: web
    name: aio-search-tool
    env: python
    runtime: python3.11
    buildCommand: |
      python -m pip install --upgrade pip
      pip install --no-cache-dir pandas==2.1.4 numpy==1.24.3
      pip install --no-cache-dir -r requirements.txt
    startCommand: "streamlit run web_app.py --server.port $PORT --server.address 0.0.0.0 --server.headless true --browser.gatherUsageStats false"
    plan: free
    healthCheckPath: /_stcore/health
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: AIRTOP_API_KEY
        sync: false
      - key: STREAMLIT_SERVER_HEADLESS
        value: true
      - key: STREAMLIT_BROWSER_GATHER_USAGE_STATS
        value: false 