[server]
headless = true
enableCORS = false
enableXsrfProtection = false
port = 8501

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#1B263B"
backgroundColor = "#F7F9FB"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#23272F"

[logger]
level = "info" 